"""
Tools exposed to the Claude agent via Anthropic tool-use.
Each tool is a plain Python function plus a JSON schema descriptor.
"""
from __future__ import annotations
import json
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from backend.data     import execute_sql_on_dataframe, summarize_result, dataframe_schema
from backend.analysis import build_analysis_plan

# ── shared dataframe ──────────────────────────────────────────────────────────
_shared_df: pd.DataFrame | None = None

def set_tool_dataframe(df: pd.DataFrame) -> None:
    global _shared_df
    _shared_df = df

def get_tool_dataframe() -> pd.DataFrame | None:
    return _shared_df


# ── tool implementations ──────────────────────────────────────────────────────

def inspect_dataset_schema() -> str:
    """Return column names, types, and sample rows so the agent understands the data."""
    if _shared_df is None:
        return "Error: No dataset loaded. Please upload a CSV file."
    return dataframe_schema(_shared_df)


def analyze_business_data(
    metric:     str = "revenue",
    group_by:   str = "product",
    date_grain: str = "",
    chart_type: str = "",
    filter_sql: str = "",
) -> dict:
    """
    Perform statistical analysis on the dataset and return a numeric summary
    plus a Plotly figure (stored in a shared slot for the UI to pick up).
    """
    global _last_fig
    if _shared_df is None:
        return {"error": "No dataset loaded."}

    plan = build_analysis_plan(
        question="",
        df=_shared_df,
        group_by=group_by,
        metric=metric,
        date_grain=date_grain,
        chart_type=chart_type,
    )
    sql = plan["sql"]
    if filter_sql:
        sql = sql + f" HAVING {filter_sql}"

    try:
        result_df = execute_sql_on_dataframe(_shared_df, sql)
    except Exception as e:
        return {"error": str(e), "sql": sql}

    summary = summarize_result(result_df, _shared_df)

    # build plotly figure
    ct = plan["chart_type"]
    x, y = plan["chart_x"], plan["chart_y"]
    kwargs = dict(
        template="plotly_dark",
        title=f"{metric.title()} by {group_by.title()}",
        color_discrete_sequence=px.colors.sequential.Blues_r,
    )
    try:
        if ct == "line":
            fig = px.line(result_df,  x=x, y=y, **kwargs)
        elif ct == "pie":
            fig = px.pie(result_df,   names=x, values=y, hole=0.4, **kwargs)
        elif ct == "scatter":
            fig = px.scatter(result_df, x=x, y=y, **kwargs)
        else:
            fig = px.bar(result_df, x=x, y=y,
                         color=y, color_continuous_scale="Blues", **kwargs)
        fig.update_layout(plot_bgcolor="#151820", paper_bgcolor="#151820", font_color="#e8eaf0")
    except Exception:
        fig = None

    # store for UI
    set_last_fig(fig)

    return {
        "summary":        str(summary),
        "rows_returned":  summary.rows_returned,
        "total_revenue":  summary.total_revenue,
        "total_profit":   summary.total_profit,
        "profit_margin":  round(summary.profit_margin * 100, 2),
        "top_performer":  summary.top_dimension,
        "weak_performer": summary.weak_dimension,
        "data_preview":   result_df.head(10).to_string(index=False),
        "sql_used":       sql,
    }


def generate_pdf_report(content: str) -> str:
    """Tell the agent the PDF will be generated by the UI layer."""
    return "PDF_REQUESTED:" + content


# ── last figure slot (for UI) ─────────────────────────────────────────────────
_last_fig: go.Figure | None = None

def set_last_fig(fig: go.Figure | None) -> None:
    global _last_fig
    _last_fig = fig

def get_last_fig() -> go.Figure | None:
    return _last_fig

TOOL_SCHEMAS = [
    {
        "type": "function",
        "function": {
            "name": "inspect_dataset_schema",
            "description": "Inspect column names, data types, and sample rows.",
            "parameters": {"type": "object", "properties": {}, "required": []}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "analyze_business_data",
            "description": "Perform statistical analysis on the dataset.",
            "parameters": {
                "type": "object",
                "properties": {
                    "metric": {"type": "string"},
                    "group_by": {"type": "string"},
                    "date_grain": {"type": "string"},
                    "chart_type": {"type": "string"},
                    "filter_sql": {"type": "string"},
                }
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "generate_pdf_report",
            "description": "Compile the analysis findings into a downloadable PDF.",
            "parameters": {
                "type": "object",
                "properties": {"content": {"type": "string"}},
                "required": ["content"]
            }
        }
    }
]

# ── dispatcher ────────────────────────────────────────────────────────────────

def dispatch_tool(name: str, inputs: dict) -> str:
    if name == "inspect_dataset_schema":
        return inspect_dataset_schema()
    if name == "analyze_business_data":
        result = analyze_business_data(**inputs)
        return json.dumps(result, ensure_ascii=False)
    if name == "generate_pdf_report":
        return generate_pdf_report(**inputs)
    return f"Unknown tool: {name}"
